--liquibase formatted sql

--changeset Alik:1
create table users
(
    id         bigint                              not null generated by default as identity
        constraint pk_users
            primary key,
    created_at timestamp default current_timestamp not null,
    updated_at timestamp,
    name       varchar(200)                        not null,
    surname    varchar(200)                        not null,
    username   varchar(200)                        not null,
    password   varchar(300)                        not null
);

--changeset Alik:2-create-user_id-index
create index user_user_id_idx on users (id);

--changeset Alik:3-create-customer_username-index
create index user_user_username_idx on users (username);