--liquibase formatted sql

--changeset Alik:2
create table parcels
(
    id                                 bigint                              not null generated by default as identity
        constraint pk_parcels
            primary key,
    parcel_sending_time                timestamp default current_timestamp not null,
    parcel_approximate_acceptance_time timestamp                           not null,
    status                             varchar(50)                         not null,
    longitude                          numeric,
    latitude                           numeric,
    customer_username                  varchar(200)                        not null,
    courier_name                       varchar(200)                        not null,
    order_id                           bigint                              not null
        constraint fk_order
            references orders (id)
);

--changeset Alik:2-create-parcel_id-index
create
    index parcel_parcel_id_idx on parcels (id);